version: 2
jobs:
  build:
    working_directory: ~/poke-slots
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

            - v1-dependencies-
      - run: npm install -f
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test
          environment:
            OWNER_ADDR: 0x09a6737516Ba5cdf9f4FE397Bc31308a7623A2cc
            CADDRESS_POKE_SLOTS_TEST: 0x20c87e98e68b6ed0cac499e95ac66a4f6b473751
